### ISSUE TITLE
Undefined variable roleProvied in API.php line 37

### ISSUE THREAD

**Issue by EmTeedee** [MichaelHeerklotz/plugin-GroupPermissions#1]
Hi,

I just installed the plugin (which works great!) and get a notice in the settings about this.

> WARNING: /var/www/srv.swansdoor.org/piwik/plugins/GroupPermissions/API.php(37): Notice - Undefined variable: roleProvider - Matomo 3.6.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

Thanks for your work.

EmTeedee

**Comment by MichaelRoosz** [comment]
Hello EmTeedee,

Thank you!
The issue should be fixed with v3.6.1

Greetings,
Michael

**Comment by EmTeedee** [comment]
And it is indeed, thanks!
