### ISSUE TITLE
Maintained fork by Veepee

### ISSUE THREAD

**Issue by rockyluke** [MichaelHeerklotz/plugin-GroupPermissions#16]
Hello,

First of all thank you @MichaelRoosz & contributors for providing us such great plugin. You've done an amazing work.

We are very happy paying user of Matomo & GroupPermissions at Veepee but I seem that it's not maintained anymore and I respectfully understand that. 

We plan to maintain the fork on https://github.com/veepee-oss/matomo-plugin-grouppermissions. As a start we merged https://github.com/MichaelRoosz/plugin-GroupPermissions/pull/15 by @snake14 :pray:

Feel free to join & help us by making more & more issues / PR 😄

➡️ https://github.com/veepee-oss/matomo-plugin-grouppermissions

**Comment by MichaelRoosz** [comment]
Hello @rockyluke,

thank you for your work.

This project is still maintained by me and there will be an update for v5 at some time, but this depends on how much time I can spare for it. It is nice to hear that you are paying for Matomo, but, as I am not associated with Innocraft I have never received anything for this plugin however.

If you plan to release your plugin to the Matomo Marketplace, please choose a different name for your fork to avoid confusion. Thank you.

Greetings, Michael

**Comment by rockyluke** [comment]
My bad, if you're still active, no need for us to handle it 🙏 apology for the misunderstanding !

**Comment by MichaelRoosz** [comment]
no worries, there is enough room for two Matomo group plugins. we can also join up on this one if you would like to.

**Comment by rockyluke** [comment]
Better to collaborate ! Thanks.
