### ISSUE TITLE
Matomo 5 updater does not recognize GroupPermissions available

### ISSUE THREAD

**Issue by kingfisher77** [MichaelHeerklotz/plugin-GroupPermissions#19]
Thank you very much for this useful plugin.

The updater on our Matomo instance does not recognize GroupPermissions available for Version 5.

It should, right? Or what should i do?

```
Note: some plugins are not compatible with Matomo 5.0.1. We will update them if there is an update on the Marketplace, otherwise we will disable them when you upgrade:

GroupPermissions
LoginLdap
```

**Comment by rockyluke** [comment]
This has been fixed, plugin can be installed on Matomo 5.x.
