### ISSUE TITLE
Compatibility with matomo 4

### ISSUE THREAD

**Issue by nightvisi0n** [MichaelHeerklotz/plugin-GroupPermissions#2]
Matomo 4 will be released soon, and this plugin is no longer listed in the plugin marketplace for this version (see https://plugins.matomo.org/GroupPermissions#description `Requirements: Matomo >=3.6.0,<4.0.0-b1`).

**Comment by camlafit** [comment]
Hello

Any evolve about this ?

Thanks a lot

**Comment by MichaelRoosz** [comment]
Thank you for letting me know.

I will create a new release in the next few days.

**Comment by VinnyMacchiaAi** [comment]
Hello, is there any update on getting this working with 4.0? 

Thanks!

**Comment by mi2git** [comment]
Hi
Is there any update on this issue or won't there be any updated version for Matomo 4.x?
(This is the last blocker before we can update our installation to v 4.x)

Thanks a lot...

**Comment by tomper00** [comment]
I upgraded the plugin locally to Matomo 4 and did a testrun and the functionality seems to work fine under Matomo 4.
I made a pull request as well, but I guess you want to make a separate branch for Matomo 4 before you commit this.

**Comment by tomper00** [comment]
@MichaelRoosz did you have time to have a look at the pull request? 
I think it would make sense to create a new branch for Matomo 4 and merge this.

**Comment by n0r** [comment]
Hi @tomper00,

when inserting your mr changes into my plugin installation, the version number in Matomos plugin overview doesn't change.
Still showing 3.9.1.
Am i missing a step, after changing plugin.json?

Can you help me?
I need to get the plugin back working for a client.

Thanks Tim

**Comment by tomper00** [comment]
@n0r Updating the plugin.json should work, we tested this in several environments. 
Perhaps you need to clear the cache or even restart your environments.

**Comment by MichaelRoosz** [comment]
Thank you everbody, I have merged the PR, did some testing with Matomo 4.8.0, fixed a minor issue and releaed version 4.0.1.
More testing will follow soon,
