### ISSUE TITLE
Too easy to apply permission to all sites

### ISSUE THREAD

**Issue by mwithheld** [MichaelHeerklotz/plugin-GroupPermissions#5]
It is far too easy to not really see the "Choose a website" dropdown, and then apply a view/write permission for a group to all sites.  There's no undo or "Are you sure?".  With numerous sites/groups it'd take a long time to undo this manually, and of course there's no record of what the permission for each site were before you did this.

I suggest a "Are you sure you want to apply this to *all* sites?" kind of prompt.

**Comment by MichaelRoosz** [comment]
Hello @mwithheld,

thank you for your feedback.

Actually there is already an "Are you sure?" prompt. Maybe you did not notice it because the site selection was broken in version 4.0.1.

Please check version 4.0.4.

Greetings,
Michael
