### ISSUE TITLE
Apply to all websites button raw HTML strong tag

### ISSUE THREAD

**Issue by mwithheld** [MichaelHeerklotz/plugin-GroupPermissions#6]
The "Apply to all websites" button shows as <"strong>Apply to all websites</strong>" -- i.e. the strong tags show as text

URL: /index.php?module=GroupPermissions&action=index&date=yesterday&period=day&idSite=3&show=access&idGroup=1&activated=
Screenshot: https://tinyurl.com/y68yvu8q
Win10/Firefox latest

**Comment by MichaelRoosz** [comment]
Hello @mwithheld,

thank you for letting me know.
It is fixed in version 4.0.4.

Greetings,
Michael
