### ISSUE TITLE
Change permission for 1 site, try another site: permissions table does not refresh

### ISSUE THREAD

**Issue by mwithheld** [MichaelHeerklotz/plugin-GroupPermissions#7]
Under the Manage Access tab, if I change permissions for one site I see the Done message, but changing the siteSelector dropdown to another site does not refresh the info in the permissions table.  There's no indication the change of site worked/failed, and no network requests happening here (in case there should be), no console error.

URL: /index.php?module=GroupPermissions&action=index&date=yesterday&period=day&idSite=3&show=access&idGroup=1&activated=
Screenshot: https://tinyurl.com/y63yf47a
Win11/Firefox

**Comment by MichaelRoosz** [comment]
Hello @mwithheld,

thank you for letting me know.
It is fixed in version 4.0.4.

Greetings,
Michael
