### ISSUE TITLE
Add an autocompletion field to find existing users

### ISSUE THREAD

**Issue by Chardonneaur** [MichaelHeerklotz/plugin-GroupPermissions#8]
Hello,
Here is a feature suggest, currently the plugin does not automatically search the name of users to add them to the group created.
Could you please perform an auto completion?
Thank you,

**Comment by MichaelRoosz** [comment]
Hello @Chardonneaur,

thank you for your feedback.
Auto completion has been added in version 4.0.4.

Greetings,
Michael

**Comment by Chardonneaur** [comment]
Thank you so much @MichaelRoosz video tutorial just published here as a reward :) https://peertube.floss-marketing-school.com/w/pMtPsG8pdp6xpcUSamuAEz

**Comment by MichaelRoosz** [comment]
Great, thank you!
