### ISSUE TITLE
Translations using Weblate

### ISSUE THREAD

**Issue by Findus23** [MichaelHeerklotz/plugin-GroupPermissions#9]
Hello,

Lukas from Matomo team here. As you might know we are using Weblate (https://hosted.weblate.org/projects/matomo/) to manage Matomo translations. As Weblate makes it easier to add a git repository as a component and merge back updated translations via pull requests, I thought it would be great if more plugins in Matomo were available in the users languages if someone is interested in translating them.

If you are interested in adding your plugin, simply comment here, and I'll help you with the setup.
(I think I missed your plugin when I originally sent out messages to plugin authors)

**Comment by MichaelRoosz** [comment]
Hello @Findus23,

sounds great.
I have added the webhook according to https://developer.matomo.org/guides/maintaining-translations

Greetings,
Michael

**Comment by Findus23** [comment]
Okay, great. I have added the project to weblate:

https://hosted.weblate.org/projects/matomo/communityplugin-grouppermissions/

It will take a while until all languages are added and once this is done, you can merge the pull request and people can start translating.

I also changed two English strings to replace %s with %1$s (and similar) so that people can reorder them if it is needed in their language.

**Comment by MichaelRoosz** [comment]
Great, thank you!

**Comment by Findus23** [comment]
Okay, I think the import is ready and people can already start translating (and someone already started on the Bulgarian translation):
https://hosted.weblate.org/projects/matomo/communityplugin-grouppermissions/
